-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS
  ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
GROUP BY CATEGORY
ORDER BY CATEGORY


-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES)
FROM BOOK B
JOIN BOOK_SALES S
  ON B.BOOK_ID = S.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY