# 완료된 중고거래의 총금액이
# 70만원 이상인 사람
#   회원 ID, 닉네임, 총거래금액
# 정렬: 총거래금액

# key: B.작성자 ID (WRITER_ID) U.USER_ID

-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U
  ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY B.WRITER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY SUM(B.PRICE)