# -- 코드를 입력하세요
# SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
# FROM USER_INFO U
# JOIN ONLINE_SALE S
#   ON U.USER_ID = S.USER_ID
# WHERE U.GENDER IS NOT NULL
# GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER
# ORDER BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), U.GENDER


-- SELECT에서 만든 별칭을 GROUP BY, ORDER BY에서 사용할 수 있음
-- "회원 수 집계"이므로 DISTINCT 처리 필요
SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, U.GENDER AS GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM USER_INFO U
JOIN ONLINE_SALE S
  ON U.USER_ID = S.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER  